In [56]:
import pandas as pd 
import numpy as np

In [ ]:
df = pd.read_csv(r"C:\prj_power_consumption\householctivate.batd_power_consumption.txt", sep=';')
df.to_csv(r"C:\prj_power_consumption\prj_power\power_analysis\Scripts\a", index=False)

In [20]:
df = pd.read_csv(r"C:\prj_power_consumption\household_power_consumption.csv")
df.head()

C:\Users\123\AppData\Local\Temp\ipykernel_12492\3386957026.py:1: DtypeWarning: Columns (2,3,4,5,6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\prj_power_consumption\household_power_consumption.csv")

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,16/12/2006,17:24:00,4.216,0.418,234.840,18.400,0.000,1.000,17.0
1,16/12/2006,17:25:00,5.360,0.436,233.630,23.000,0.000,1.000,16.0
2,16/12/2006,17:26:00,5.374,0.498,233.290,23.000,0.000,2.000,17.0
3,16/12/2006,17:27:00,5.388,0.502,233.740,23.000,0.000,1.000,17.0
4,16/12/2006,17:28:00,3.666,0.528,235.680,15.800,0.000,1.000,17.0

In [21]:
df.columns

Index(['Date', 'Time', 'Global_active_power', 'Global_reactive_power',
       'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2',
       'Sub_metering_3'],
      dtype='object')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075259 entries, 0 to 2075258
Data columns (total 9 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Date                   object
 1   Time                   object
 2   Global_active_power    object
 3   Global_reactive_power  object
 4   Voltage                object
 5   Global_intensity       object
 6   Sub_metering_1         object
 7   Sub_metering_2         object
 8   Sub_metering_3         float64
dtypes: float64(1), object(8)
memory usage: 142.5+ MB

In [45]:
df['Date'] = pd.to_datetime(df['Date'],dayfirst=True)
df['Time'] = pd.to_timedelta(df['Time'])

C:\Users\123\AppData\Local\Temp\ipykernel_12492\3320087510.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['Date'] = pd.to_datetime(df['Date'],dayfirst=True)

In [46]:
df.dtypes

Date                      datetime64[ns]
Time                     timedelta64[ns]
Global_active_power               object
Global_reactive_power             object
Voltage                           object
Global_intensity                  object
Sub_metering_1                    object
Sub_metering_2                    object
Sub_metering_3                   float64
dtype: object

In [47]:
df['Time'] = df['Time'].apply(lambda x: str(x).split()[-1])

In [48]:
df.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,2006-12-16,17:24:00,4.216,0.418,234.840,18.400,0.000,1.000,17.0
1,2006-12-16,17:25:00,5.360,0.436,233.630,23.000,0.000,1.000,16.0
2,2006-12-16,17:26:00,5.374,0.498,233.290,23.000,0.000,2.000,17.0
3,2006-12-16,17:27:00,5.388,0.502,233.740,23.000,0.000,1.000,17.0
4,2006-12-16,17:28:00,3.666,0.528,235.680,15.800,0.000,1.000,17.0

In [49]:
df.to_csv(r"C:\prj_power_consumption\Cleaned_data.csv", index=False)

In [57]:
df = pd.read_csv(r"C:\prj_power_consumption\Cleaned_data.csv", parse_dates=['Date'])
df.replace('?', np.nan, inplace=True)
df['Time'] = pd.to_datetime(df['Time'], format='%H:%M:%S').dt.time
float_cols = ['Global_active_power', 'Global_reactive_power', 'Voltage',
              'Global_intensity', 'Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3']
df[float_cols] = df[float_cols].astype(float)

C:\Users\123\AppData\Local\Temp\ipykernel_12492\1387233148.py:1: DtypeWarning: Columns (2,3,4,5,6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\prj_power_consumption\Cleaned_data.csv", parse_dates=['Date'])

In [62]:
df.dtypes

Date                     datetime64[ns]
Time                             object
Global_active_power             float64
Global_reactive_power           float64
Voltage                         float64
Global_intensity                float64
Sub_metering_1                  float64
Sub_metering_2                  float64
Sub_metering_3                  float64
dtype: object

In [64]:
df.columns

Index(['Date', 'Time', 'Global_active_power', 'Global_reactive_power',
       'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2',
       'Sub_metering_3'],
      dtype='object')